import { env } from "../../config/env.js";

export const AUTH_CONSTANTS = {
  OTP_LENGTH: 6,

  OTP_EXPIRY_MINUTES: env.OTP.EXPIRY_MINUTES,

  OTP_RESEND_COOLDOWN: env.OTP.RESEND_COOLDOWN,

  OTP_MAX_ATTEMPTS: env.OTP.MAX_ATTEMPTS,

  ACCESS_TOKEN_EXPIRY: env.JWT.ACCESS_EXPIRES_IN,

  REFRESH_TOKEN_EXPIRY: env.JWT.REFRESH_EXPIRES_IN,
} as const;
